# Generated by Django 3.2.8 on 2022-02-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responden',
            fields=[
                ('id_responden', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('name_company', models.CharField(max_length=100)),
                ('businness_field', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeightLRFM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_responden', models.IntegerField()),
                ('w_length', models.FloatField()),
                ('w_recency', models.FloatField()),
                ('w_frequency', models.FloatField()),
                ('w_monetary', models.FloatField()),
                ('score_input', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeightRFM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_responden', models.IntegerField()),
                ('w_recency', models.FloatField()),
                ('w_frequency', models.FloatField()),
                ('w_monetary', models.FloatField()),
                ('score_input', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
