# Generated by Django 3.2.8 on 2022-02-25 11:55

from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responden',
            name='birth_date',
            field=models.DateField(default=datetime.now()),
            preserve_default=False,
        ),
    ]
