# Generated by Django 3.2.8 on 2022-02-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weighting', '0003_alter_responden_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responden',
            name='birth_date',
        ),
    ]
